arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false #Dùng AppLocalizations.of(context) mà không phải thêm !.
required-resource-attributes: true #bắt buộc key template có metadata, giúp translator hiểu ngữ cảnh.
use-escaping: true
format: true
untranslated-messages-file: .dart_tool/untranslated_messages.json #phục vụ kiểm tra bản dịch còn thiếu trong CI.
