// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw43D9e6TJ5Dp7lIo3eAZrRMF0GpY55vk',
    appId: '1:188531575867:web:d57b16fc83fe1addf9a01e',
    messagingSenderId: '188531575867',
    projectId: 'movieapp-c3847',
    authDomain: 'movieapp-c3847.firebaseapp.com',
    storageBucket: 'movieapp-c3847.firebasestorage.app',
    measurementId: 'G-NLN6LDBT0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjp9T7PxQfgzJ0QxKNio9bdOlRUA-tAXM',
    appId: '1:188531575867:android:9f6cd21491b179a5f9a01e',
    messagingSenderId: '188531575867',
    projectId: 'movieapp-c3847',
    storageBucket: 'movieapp-c3847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfy7lacI7z_4kEfrSTB_3BILaRbtJRCQ8',
    appId: '1:188531575867:ios:a1ae36692b291793f9a01e',
    messagingSenderId: '188531575867',
    projectId: 'movieapp-c3847',
    storageBucket: 'movieapp-c3847.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfy7lacI7z_4kEfrSTB_3BILaRbtJRCQ8',
    appId: '1:188531575867:ios:a1ae36692b291793f9a01e',
    messagingSenderId: '188531575867',
    projectId: 'movieapp-c3847',
    storageBucket: 'movieapp-c3847.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw43D9e6TJ5Dp7lIo3eAZrRMF0GpY55vk',
    appId: '1:188531575867:web:cd468d974998b38ef9a01e',
    messagingSenderId: '188531575867',
    projectId: 'movieapp-c3847',
    authDomain: 'movieapp-c3847.firebaseapp.com',
    storageBucket: 'movieapp-c3847.firebasestorage.app',
    measurementId: 'G-E1E5L68530',
  );
}
