// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:movie_app/common/models/favorite_movie_entry.dart';
import 'package:movie_app/common/models/watch_history_entry.dart';
import 'package:movie_app/common/models/watch_progress_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteMovieEntryAdapter());
    registerAdapter(WatchHistoryEntryAdapter());
    registerAdapter(WatchProgressModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteMovieEntryAdapter());
    registerAdapter(WatchHistoryEntryAdapter());
    registerAdapter(WatchProgressModelAdapter());
  }
}
